ERP.Web/Areas/Purchases/Models/Providers/ContactViewModel.cs
using ERP.Domain.Entities.Purchases.Providers;
using System.ComponentModel.DataAnnotations;

namespace ERP.Web.Areas.Purchases.Models.Providers
{
    public class ContactViewModel
    {
        public int Id { get; set; }
        public int ConcurrencyToken { get; set; }

        public string Name { get; set; }
        public string Charge { get; set; }
        public string MobilePhoneNumber { get; set; }
        public string PhoneNumber { get; set; }

        [EmailAddress]
        public string Email { get; set; }

        public string SubsidiaryNumber { get; set; }

        public int ProviderId { get; set; }
        public Provider Provider { get; set; }
    }
}

ERP.Web/Areas/Purchases/Models/Providers/FinancialInformationViewModel.cs
using ERP.Domain.Entities.Purchases.Providers;

namespace ERP.Web.Areas.Purchases.Models.Providers
{
    public class FinancialInformationViewModel
    {
        public int Id { get; set; }
        public int ConcurrencyToken { get; set; }

        public string Bank { get; set; }
        public string AccountType { get; set; }
        public string AccountNumber { get; set; }
        public string CBU { get; set; }
        public string Observations { get; set; }

        public int ProviderId { get; set; }
        public Provider Provider { get; set; }
    }
}

ERP.Web/Areas/Purchases/Models/Providers/ProviderViewModel.cs
using ERP.Domain.Entities.Commons;
using ERP.Domain.Entities.Lists;
using ERP.Web.Areas.Purchases.Models.QuoteRequest;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Collections.Generic;

namespace ERP.Web.Areas.Purchases.Models.Providers
{
    public class ProviderViewModel
    {
        public int Id { get; set; }
        public int ConcurrencyToken { get; set; }

        public string Name { get; set; }
        public string BusinessName { get; set; }

        public int CountryId { get; set; }
        public SelectList Countries { get; set; }
        public Country Country { get; set; }
        public int? StateId { get; set; }
        public SelectList States { get; set; }
        public State State { get; set; }
        public int? CityId { get; set; }
        public SelectList Cities { get; set; }
        public City City { get; set; }

        public string Address { get; set; }
        public string PostalCode { get; set; }

        public int DocumentTypeId { get; set; }
        public SelectList DocumentTypes { get; set; }
        public DocumentType DocumentType { get; set; }
        public string DocumentNumber { get; set; }

        public int IVAConditionId { get; set; }
        public SelectList IVAConditions { get; set; }
        public IVACondition IVACondition { get; set; }

        public string GrossIncome { get; set; }
        public string WebPage { get; set; }

        public bool IsActive { get; set; }
        public string ProviderType { get; set; }
        public SelectList ProviderTypes { get; set; } = new SelectList(new List<string> { "Productos", "Servicios", "Transporte" });
        public string Observations { get; set; }

        public IList<ContactViewModel> Contacts { get; set; }

        public IList<SubsidiaryViewModel> Subsidiaries { get; set; }

        public IList<FinancialInformationViewModel> FinancialInformations { get; set; }

        public ICollection<RelProviderProductViewModel> RelProviderProducts { get; set; } = new List<RelProviderProductViewModel>();

        public ICollection<RelProviderStationViewModel> RelProviderStations { get; set; } = new List<RelProviderStationViewModel>();

        public ICollection<RelQuoteRequestProviderViewModel> RelQuoteRequestProviders { get; set; } = new List<RelQuoteRequestProviderViewModel>();

        public string getNameOrBussinessName
        {
            get
            {
                if (this.Name != null && this.Name != "")
                {
                    return this.Name;
                }
                else
                {
                    return this.BusinessName;
                }
            }
        }

        public string getBussinessNameOrName
        {
            get
            {
                if (this.BusinessName != null && this.BusinessName != "")
                {
                    return this.BusinessName;
                }
                else
                {
                    return this.Name;
                }
            }
        }

        public bool calledFromAnotherArea { get; set; }

        public ProviderViewModel()
        {
            Contacts = new List<ContactViewModel>();
            Subsidiaries = new List<SubsidiaryViewModel>();
            FinancialInformations = new List<FinancialInformationViewModel>();
        }
    }
}

ERP.Web/Areas/Purchases/Models/Providers/RelProviderProductViewModel.cs
using ERP.Web.Areas.ProductMod.Models;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.ComponentModel.DataAnnotations;

namespace ERP.Web.Areas.Purchases.Models.Providers
{
    public class RelProviderProductViewModel
    {
        public int Id { get; set; }
        public int ConcurrencyToken { get; set; }

        public int ProviderId { get; set; }
        public ProviderViewModel Provider { get; set; }

        public int ProductId { get; set; }
        public SelectList Products { get; set; }
        public ProductViewModel Product { get; set; }

        public string Brand { get; set; }
        public string ProviderCode { get; set; }

        [Required(ErrorMessage = "Unit measure value must be completed.")]
        public int UnitMeasureId { get; set; }
        public UnitMeasureViewModel UnitMeasure { get; set; }
        public SelectList UnitsMeasure { get; set; }

        // WidthUnitMeasure
        [DisplayFormat(DataFormatString = "{0:n2}", ApplyFormatInEditMode = true)]
        public decimal? Width { get; set; }
        public int? WidthUnitMeasureId { get; set; }
        public UnitMeasureViewModel WidthUnitMeasure { get; set; }

        // LenghtUnitMeasure
        [DisplayFormat(DataFormatString = "{0:n2}", ApplyFormatInEditMode = true)]
        public decimal? Lenght { get; set; }
        public int? LengthUnitMeasureId { get; set; }
        public UnitMeasureViewModel LengthUnitMeasure { get; set; }

        // WeightUnitMeasure
        [DisplayFormat(DataFormatString = "{0:n2}", ApplyFormatInEditMode = true)]
        public decimal? Weight { get; set; }
        public int? WeightUnitMeasureId { get; set; }
        public UnitMeasureViewModel WeightUnitMeasure { get; set; }

        // WeightUnitMeasure
        [DisplayFormat(DataFormatString = "{0:n2}", ApplyFormatInEditMode = true)]
        public decimal? Height { get; set; }
        public int? HeightUnitMeasureId { get; set; }
        public UnitMeasureViewModel HeightUnitMeasure { get; set; }

        // PresentationUnitMeasure
        [DisplayFormat(DataFormatString = "{0:n2}", ApplyFormatInEditMode = true)]
        public decimal? PresentationQuantity { get; set; }
        public int? PresentationUnitMeasureId { get; set; }
        public UnitMeasureViewModel PresentationUnitMeasure { get; set; }

        public string Observations { get; set; }

        [DisplayFormat(DataFormatString = "{0:n2}", ApplyFormatInEditMode = true)]
        public decimal DollarPrice { get; set; }

        [DisplayFormat(DataFormatString = "{0:n2}", ApplyFormatInEditMode = true)]
        public decimal PesosPrice { get; set; }

        public int? PriceUnitMeasureId { get; set; }
        public UnitMeasureViewModel PriceUnitMeasure { get; set; }

        public bool viewDetails { get; set; }
        public bool editFromAllProductsProviders { get; set; }

    }
}

ERP.Web/Areas/Purchases/Controllers/Provider/ProviderController.cs
using ERP.Application.Constants;
using ERP.Application.DTOs.Entities.Commons;
using ERP.Application.DTOs.Entities.Purchases.Providers;
using ERP.Application.Interfaces.ViewManagers.Commons;
using ERP.Application.Interfaces.ViewManagers.Lists;
using ERP.Application.Interfaces.ViewManagers.ProductMod;
using ERP.Application.Interfaces.ViewManagers.Purchases.Providers;
using ERP.Application.Specification.Commons.UnitMeasureSpecifications;
using ERP.Application.Specification.Purchases.Providers;
using ERP.Language;
using ERP.Web.Abstractions;
using ERP.Web.Areas.Commons.Models;
using ERP.Web.Areas.Lists.Models;
using ERP.Web.Areas.ProductMod.Models;
using ERP.Web.Areas.Purchases.Models.Providers;
using ERP.Web.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Localization;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ERP.Web.Areas.Purchases.Controllers.Provider
{
    [Area("Purchases")]
    public class ProviderController : BaseController<ProviderController>
    {
        private readonly IProviderViewManager _providerViewManager;
        private readonly IStringLocalizer<SharedResource> _localizer;

        private readonly ICountryViewManager _countryViewManager;
        private readonly IDocumentTypeViewManager _documentTypeViewManager;
        private readonly IIVAConditionViewManager _iVAConditionViewManager;
        private readonly IStateViewManager _stateViewManager;
        private readonly ICityViewManager _cityViewManager;

        private readonly IContactViewManager _contactViewManager;
        private readonly ISubsidiaryViewManager _subsidiaryViewManager;
        private readonly IFinancialInformationViewManager _financialInformationViewManager;
        private readonly IRelProviderStationViewManager _relProviderStationViewManager;
        private readonly IStationViewManager _stationViewManager;
        private readonly IUnitMeasureViewManager _unitMeasureViewManager;

        public ProviderController(IProviderViewManager providerViewManager, IStringLocalizer<SharedResource> localizer, ICountryViewManager countryViewManager, IDocumentTypeViewManager documentTypeViewManager, IIVAConditionViewManager iVAConditionViewManager, IStateViewManager stateViewManager, ICityViewManager cityViewManager, IContactViewManager contactViewManager, ISubsidiaryViewManager subsidiaryViewManager, IFinancialInformationViewManager financialInformationViewManager, IRelProviderStationViewManager relProviderStationViewManager, IStationViewManager stationViewManager, IUnitMeasureViewManager unitMeasureViewManager)
        {
            _providerViewManager = providerViewManager;
            _localizer = localizer;
            _countryViewManager = countryViewManager;
            _documentTypeViewManager = documentTypeViewManager;
            _iVAConditionViewManager = iVAConditionViewManager;
            _stateViewManager = stateViewManager;
            _cityViewManager = cityViewManager;
            _contactViewManager = contactViewManager;
            _subsidiaryViewManager = subsidiaryViewManager;
            _financialInformationViewManager = financialInformationViewManager;
            _relProviderStationViewManager = relProviderStationViewManager;
            _stationViewManager = stationViewManager;
            _unitMeasureViewManager = unitMeasureViewManager;
        }

        public IActionResult Index()
        {
            var model = new ProviderViewModel();
            return View(model);
        }

        public async Task<IActionResult> LoadAll()
        {
            var response = await _providerViewManager.LoadAll();
            if (response.Succeeded)
            {
                var viewModel = _mapper.Map<List<ProviderViewModel>>(response.Data);
                return PartialView("_ViewAll", viewModel);
            }
            return null;
        }

        [Authorize(Policy = Permissions.Providers.View)]
        public async Task<JsonResult> OnGetCreateOrEdit(int id = 0, bool calledFromAnotherArea = false)
        {
            var countriesResponse = await _countryViewManager.LoadAll();
            var documentTypesResponse = await _documentTypeViewManager.LoadAll();
            var ivaConditionsResponse = await _iVAConditionViewManager.LoadAll();

            if (id == 0)
            {
                // Create new provider
                var providerViewModel = new ProviderViewModel();

                if (countriesResponse.Succeeded)
                {
                    var countryViewModel = _mapper.Map<List<CountryDTO>>(countriesResponse.Data);
                    providerViewModel.Countries = new SelectList(countryViewModel, nameof(CountryViewModel.Id), nameof(CountryViewModel.Denomination), null, null);
                }

                if (documentTypesResponse.Succeeded)
                {
                    var documentTypeViewModel = _mapper.Map<List<DocumentTypeDTO>>(documentTypesResponse.Data);
                    providerViewModel.DocumentTypes = new SelectList(documentTypeViewModel, nameof(DocumentTypeViewModel.Id), nameof(DocumentTypeViewModel.Description), null, null);
                }

                if (ivaConditionsResponse.Succeeded)
                {
                    var ivaConditionTypeViewModel = _mapper.Map<List<IVAConditionViewModel>>(ivaConditionsResponse.Data);
                    providerViewModel.IVAConditions = new SelectList(ivaConditionTypeViewModel, nameof(IVAConditionViewModel.Code), nameof(IVAConditionViewModel.Description), null, null);
                }

                providerViewModel.calledFromAnotherArea = calledFromAnotherArea;

                return new JsonResult(new { isValid = true, html = await _viewRenderer.RenderViewToStringAsync("_CreateOrEdit", providerViewModel) });

            }
            else
            {
                // Update provider
                //var response = await _providerViewManager.GetByIdAsync(id);
                var response = await _providerViewManager.FindBySpecification(new ProviderByIdSpecifications(id));
                if (response.Succeeded)
                {
                    var providerViewModel = _mapper.Map<ProviderViewModel>(response.Data.First());

                    // Load contacts
                    var contactsByProvider = await _contactViewManager.GetContactsByProviderId(id);
                    if (contactsByProvider.Count > 0)
                    {
                        providerViewModel.Contacts = _mapper.Map<List<ContactViewModel>>(contactsByProvider);
                    }

                    // Load subsidiaries
                    var subsidiariesByProvider = await _subsidiaryViewManager.GetSubsidiariesByProviderId(id);
                    if (subsidiariesByProvider.Count > 0)
                    {
                        providerViewModel.Subsidiaries = _mapper.Map<List<SubsidiaryViewModel>>(subsidiariesByProvider);
                        foreach (var s in providerViewModel.Subsidiaries)
                        {
                            var countriesViewModel = _mapper.Map<List<CountryViewModel>>(countriesResponse.Data);
                            //s.Countries = countriesViewModel;
                            s.CountriesList = new SelectList(countriesViewModel, nameof(CountryViewModel.Id), nameof(CountryViewModel.Denomination), null, null);

                            var states = await _stateViewManager.GetStatesByCountryIdAsync(s.CountryId);
                            var statesViewModel = _mapper.Map<List<StateViewModel>>(states);
                            //s.States = statesViewModel;
                            s.StatesList = new SelectList(statesViewModel, nameof(StateViewModel.Id), nameof(StateViewModel.Name), null, null);

                            var cities = await _cityViewManager.GetCitiesByStateIdAsync(s.StateId);
                            var citiesViewModel = _mapper.Map<List<CityViewModel>>(cities);
                            //s.Cities = citiesViewModel;
                            s.CitiesList = new SelectList(citiesViewModel, nameof(CityViewModel.Id), nameof(CityViewModel.Name), null, null);
                        }
                    }

                    // Load financial information
                    var financialInfosByProvider = await _financialInformationViewManager.GetFinancialInfosByProviderId(id);
                    if (financialInfosByProvider.Count > 0)
                    {
                        providerViewModel.FinancialInformations = _mapper.Map<List<FinancialInformationViewModel>>(financialInfosByProvider);
                    }

                    if (countriesResponse.Succeeded)
                    {
                        var countryViewModel = _mapper.Map<List<CountryViewModel>>(countriesResponse.Data);
                        providerViewModel.Countries = new SelectList(countryViewModel, nameof(CountryViewModel.Id), nameof(CountryViewModel.Denomination), null, null);
                    }

                    if (providerViewModel.StateId != null)
                    {
                        var states = await _stateViewManager.GetStatesByCountryIdAsync(providerViewModel.CountryId);
                        var statesViewModel = _mapper.Map<List<StateViewModel>>(states);
                        providerViewModel.States = new SelectList(statesViewModel, nameof(StateViewModel.Id), nameof(StateViewModel.Name), null, null);
                    }

                    if (providerViewModel.CityId != null)
                    {
                        var cities = await _cityViewManager.GetCitiesByStateIdAsync(providerViewModel.StateId);
                        var citiesViewModel = _mapper.Map<List<CityViewModel>>(cities);

ERP.Web/Areas/Purchases/Views/Provider/Index.cshtml
@using Microsoft.AspNetCore.Mvc.Localization
@inject IHtmlLocalizer<ERP.Language.SharedResource> localizer
@{
    ViewData["Title"] = localizer["Providers"];
}
@using ERP.Web.Areas.Purchases.Models.Providers
@model ProviderViewModel

<head>
    <link rel="stylesheet" href="~/css/Purchases/Providers/providers.css" />
</head>
<body>

    <div class="card">

        <div id="viewAll" class="card-body table-responsive">

        </div>

    </div>
</body>

@section Scripts
{
    <script src="~/js/site.js"></script>
    <script>

        $(document).ready(function () {

            let providersTable = $("#providersTable").DataTable({
                "oLanguage": @localizer["LanguageDataTable"],
            });

            loadData();

        });

        function loadData() {
            $('#viewAll').load('/purchases/provider/LoadAll');
        }

    </script>
}

ERP.Web/Areas/Purchases/Views/Provider/WorkStationByProvider.cshtml
@using Microsoft.AspNetCore.Mvc.Localization
@inject IHtmlLocalizer<ERP.Language.SharedResource> localizer
@{
    ViewData["Title"] = localizer["Work stations for: {0}", ViewBag.ProviderName];
}
@using ERP.Web.Areas.Purchases.Models.Providers
@model RelProviderStationViewModel

<head>
    <link rel="stylesheet" href="~/css/Purchases/Providers/providers.css" />
</head>
<body>

    <div class="card">

        <div id="viewAll" class="card-body table-responsive">

        </div>

    </div>
</body>

@section Scripts
    {
    <script src="~/js/site.js"></script>
    <script>
        $(document).ready(function () {

            let relProviderStationsTable = $("#relProviderStationsTable").DataTable({
                "oLanguage": @localizer["LanguageDataTable"],
            });

            loadData();

        });

        function loadData() {
            $('#viewAll').load('/purchases/provider/LoadAllWorkStationsByProvider?id=@Model.ProviderId');
        }
    </script>
}

ERP.Web/Areas/Purchases/Views/Provider/_CreateOrEditProviderStation.cshtml
@using Microsoft.AspNetCore.Mvc.Localization
@using ERP.Web.Areas.Purchases.Models.Providers
@inject IHtmlLocalizer<ERP.Language.SharedResource> localizer
@model RelProviderStationViewModel

<form id="create-form" method="post" asp-controller="Provider" asp-action="OnPostCreateOrEditProviderStation" asp-route-id="@Model.Id" onsubmit="return jQueryModalPost(this);" enctype="multipart/form-data">

    <div class="form-row">
        <input type="hidden" asp-for="ConcurrencyToken" name="ConcurrencyToken" class="form-control">

        <input type="hidden" asp-for="ProviderId" name="ProviderId" class="form-control">

        <div class="col-md-12 mb-3">
            <label asp-for="StationId" class="control-label">@localizer["Work Station"]</label>
            <select name="StationId" class="form-control select2bs4" id="Stations" asp-for="StationId" asp-items="@Model.Stations">
                <option value="-1">@localizer["Select work station"]</option>
            </select>
            <span asp-validation-for="StationId" class="text-danger"></span>
        </div>

        <div class="col-md-12 mt-3">
            <label class="font-weight-normal">@localizer["Price per:"]</label>
            <div class="form-row">

                <div class="col-md-4 mb-3">
                    <label asp-for="PriceUnitMeasureId" class="control-label">@localizer["Quotation unit measure"]</label>
                    <select name="PriceUnitMeasureId" class="form-control select2bs4" id="PriceUnitMeasures" asp-for="PriceUnitMeasureId" asp-items="@Model.UnitsMeasure.Where(u => u.Value == "1" || u.Value == "2" || u.Value == "16" || u.Value == "17" || u.Value == "18" || u.Value == "23" || u.Value == "22" || u.Value == "31" || u.Value == "32" || u.Value == "33" || u.Value == "36" || u.Value == "37" || u.Value == "19" || u.Value == "38")">
                    </select>
                    <span asp-validation-for="PriceUnitMeasureId" class="text-danger"></span>
                </div>

                <div class="col-md-2 mb-3">
                    <label asp-for="PesosPrice" class="control-label">@localizer["Pesos price"]</label>
                    <input id="PesosPrice" type="text" name="PesosPrice" asp-for="PesosPrice" class="form-control" onkeypress="return validateIsNumber(event);" />
                    <span asp-validation-for="PesosPrice" class="text-danger"></span>
                </div>

                <div class="col-md-2 mb-3">
                    <label asp-for="DollarPrice" class="control-label">@localizer["Dollar price"]</label>
                    <input id="DollarPrice" type="text" name="DollarPrice" asp-for="DollarPrice" class="form-control" onkeypress="return validateIsNumber(event);" />
                    <span asp-validation-for="DollarPrice" class="text-danger"></span>
                </div>

                <div class="col-md-4 mb-3">
                    <label hidden id="lblActualizacionDolar" class="control-label">@localizer["Update schedule 4:00 p.m."]</label>
                    <div id="divTableDollarExchange" class="table-sm mt-1 ml-1">
                        <table id="DollarExchangeTable" class="w-100">
                            <thead class="bg-thead">
                                <tr>
                                    <th></th>
                                    <th></th>
                                    <th>@localizer["Purchase"]</th>
                                    <th>@localizer["Sale"]</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td id="date" class="w-auto"></td>
                                    <td class="w-auto">@localizer["Dollar"]</td>
                                    <td id="purchasePrice" class="w-auto"></td>
                                    <td id="salePrice" class="w-auto"></td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>

            </div>

        </div>

    </div>

    <div id="buttons-div" class="form-group justify-content-between">
        <button id="btn-save" type="submit" class="btn btn-primary">@localizer["Save"]</button>
        <button type="submit" class="btn btn-default close-button" data-dismiss="modal"> @localizer["Cancel"]</button>
    </div>

</form>

<script src="~/js/site.js"></script>
<script type="text/javascript">
    $(document).ready(function () {

        /* Format decimals */
        const decimalInputsIds = ['PesosPrice', 'DollarPrice'];

        let pesosPrice = document.getElementById('PesosPrice');
        let dollarPrice = document.getElementById('DollarPrice');
        let purchasePrice = document.getElementById('purchasePrice');
        let salePrice = document.getElementById('salePrice');
        let date = document.getElementById('date');

        $('#Stations').select2({
            theme: "bootstrap4",
            escapeMarkup: function (m) {
                return m;
            }
        });

        $('#PriceUnitMeasures').select2({
            theme: "bootstrap4",
            placeholder: "@localizer["Select unit measure"]",
            escapeMarkup: function (m) {
                return m;
            }
        });

        if ((pesosPrice != null && $('#PesosPrice').val().trim() != "0,00") || (dollarPrice != null && $('#DollarPrice').val().trim() != "0,00")) {
            $('#DollarExchangeTable').prop('hidden', false);
            $('#lblActualizacionDolar').prop('hidden', false);

            $.ajax({
                url: '/purchases/providerproduct/GetDollarQuotation',
                method: 'get',
                dataType: 'json',
                success: function (response) {

                    date.innerHTML = "";
                    date.innerHTML = response.date;

                    purchasePrice.innerHTML = "";
                    purchasePrice.innerHTML = format_number_to_decimal((response.purchasePrice), 2, ',', '.');
                    salePrice.innerHTML = "";
                    salePrice.innerHTML = format_number_to_decimal((response.salePrice), 2, ',', '.');
                }
            });

        } else {
            $('#DollarExchangeTable').prop('hidden', true);
        }

        if (@Model.Id != 0) {
            getValueForPesosAndDollar();
        }

        $('#PesosPrice').change(function () {

            let chars = { '.': '', ',': '.' };

            if ($('#PesosPrice').val().trim() != 0) {

                $.ajax({
                    url: '/purchases/providerproduct/GetDollarQuotation',
                    method: 'get',
                    data: { pesosInput: pesosPrice.value.replace(/[.,]/g, c => chars[c]), dollarInput: 0 },
                    dataType: 'json',
                    success: function (response) {
                        dollarPrice.value = format_number_to_decimal((response.pesosToDollar), 2, ',', '.');

                        if (response.salePrice == 0 && response.purchasePrice == 0) {
                            $('#DollarExchangeTable').prop('hidden', true);
                            $('#lblActualizacionDolar').prop('hidden', true);
                        } else {
                            $('#DollarExchangeTable').prop('hidden', false);
                            $('#lblActualizacionDolar').prop('hidden', false);
                        }

                        date.innerHTML = "";
                        date.innerHTML = response.date;

                        purchasePrice.innerHTML = "";
                        purchasePrice.innerHTML = format_number_to_decimal((response.purchasePrice), 2, ',', '.');
                        salePrice.innerHTML = "";
                        salePrice.innerHTML = format_number_to_decimal((response.salePrice), 2, ',', '.');
                    }
                });

            }
        });

        $('#DollarPrice').change(function () {

            let chars = { '.': '', ',': '.' };

            if ($('#DollarPrice').val().trim() != 0) {

                $.ajax({
                    url: '/purchases/providerproduct/GetDollarQuotation',
                    method: 'get',
                    data: { pesosInput: 0, dollarInput: dollarPrice.value.replace(/[.,]/g, c => chars[c]) },
                    dataType: 'json',
                    success: function (response) {

                        pesosPrice.value = format_number_to_decimal((response.dollarToPesos), 2, ',', '.');

                        if (response.salePrice == 0 && response.purchasePrice == 0) {
                            $('#DollarExchangeTable').prop('hidden', true);
                            $('#lblActualizacionDolar').prop('hidden', true);
                        } else {
                            $('#DollarExchangeTable').prop('hidden', false);
                            $('#lblActualizacionDolar').prop('hidden', false);
                        }

                        date.innerHTML = "";
                        date.innerHTML = response.date;

                        purchasePrice.innerHTML = "";
                        purchasePrice.innerHTML = format_number_to_decimal((response.purchasePrice), 2, ',', '.');
                        salePrice.innerHTML = "";
                        salePrice.innerHTML = format_number_to_decimal((response.salePrice), 2, ',', '.');
                    }
                });

            }
        });

        validateDecimalsNumbersOnInput(decimalInputsIds);

    });

    function getValueForPesosAndDollar() {
        let chars = { '.': '', ',': '.' };
        if ($('#DollarPrice').val().trim() != 0) {
            $.ajax({
                url: '/purchases/providerproduct/GetDollarQuotation',
                method: 'get',
                data: { pesosInput: 0, dollarInput: $('#DollarPrice').val().replace(/[.,]/g, c => chars[c]) },
                dataType: 'json',
                success: function (response) {
                    $('#PesosPrice').val(format_number_to_decimal((response.dollarToPesos), 2, ',', '.'));
                }
            });
        }
    }
</script>