ERP.Web/Areas/Production/Models/WorkOrderHeader/WorkOrderHeaderViewModel.cs
using ERP.Web.Areas.Admin.Models;
using ERP.Web.Areas.Production.Models.WorkActivity;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;

namespace ERP.Web.Areas.Production.Models
{
    public class WorkOrderHeaderViewModel
    {
        public int Id { get; set; }
        public int WorkOrderHeaderNumber { get; set; }
        public string Observation { get; set; }
        public DateTime CreatedOn { get; set; }
        public ICollection<WorkOrderViewModel> WorkOrders { get; set; } = new List<WorkOrderViewModel>();
        public List<WorkActivityViewModel> WorkActivities { get; set; } = new List<WorkActivityViewModel>();
        public List<WorkActivityGroupViewModel> WorkActivitiesGroupsByStation { get; set; } = new List<WorkActivityGroupViewModel>();
        public IList<UserViewModel> UsersList { get; set; }
        public SelectList UsersSelectList { get; set; }
        public string StationsIds
        {
            get
            {
                int[] stationsIds = Array.Empty<int>();
                if (this.WorkActivitiesGroupsByStation != null)
                {
                    stationsIds = this.WorkActivitiesGroupsByStation.Select(group => group.GroupStation.Id).ToArray();
                }
                return string.Join(',', stationsIds);
            }
        }

    }
}

ERP.Web/Areas/Production/Controllers/WorkOrderHeaderController.cs
using ERP.Application.Constants;
using ERP.Application.DTOs.Entities.Production;
using ERP.Application.Interfaces.ViewManagers.Production;
using ERP.Application.Interfaces.ViewManagers.ProductMod;
using ERP.Application.Specification.Production.WorkActivitySpecifications;
using ERP.Application.Specification.Production.WorkOrderHeaderSpecifications;
using ERP.Application.Specification.Production.WorkOrderItemSpecifications;
using ERP.Infrastructure.DbContexts;
using ERP.Language;
using ERP.Web.Abstractions;
using ERP.Web.Areas.Admin.Models;
using ERP.Web.Areas.Production.Models;
using ERP.Web.Areas.Production.Models.WorkActivity;
using ERP.Web.Areas.ProductMod.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Localization;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ERP.Web.Areas.Production.Controllers
{
    [Area("Production")]
    public class WorkOrderHeaderController : BaseController<WorkOrderHeaderController>
    {
        private readonly IStringLocalizer<SharedResource> _localizer;
        private readonly IWorkOrderHeaderViewManager _workOrderHeaderViewManager;
        private readonly IWorkActivityViewManager _workActivityViewManager;
        private readonly IStationViewManager _stationViewManager;
        private readonly IWorkOrderItemViewManager _workOrderItemViewManager;
        private readonly IWorkActionViewManager _workActionViewManager;
        private IdentityContext _identityContext;

        public WorkOrderHeaderController(IStringLocalizer<SharedResource> localizer, IWorkOrderHeaderViewManager workOrderHeaderViewManager, IWorkActivityViewManager workActivityViewManager, IStationViewManager stationViewManager, IWorkOrderItemViewManager workOrderItemViewManager, IWorkActionViewManager workActionViewManager, IdentityContext identityContext)
        {
            _localizer = localizer;
            _workOrderHeaderViewManager = workOrderHeaderViewManager;
            _workActivityViewManager = workActivityViewManager;
            _stationViewManager = stationViewManager;
            _workOrderItemViewManager = workOrderItemViewManager;
            _workActionViewManager = workActionViewManager;
            _identityContext = identityContext;
        }

        [Authorize(Policy = Permissions.WorkOrders.View)]
        public async Task<JsonResult> OnGetWorkOrderHeader(int idWorkOrder = 0)
        {
            try
            {
                var response = await _workOrderHeaderViewManager.FindBySpecification(new WorkOrderHeaderByWorkOrderSpecification(idWorkOrder));
                if (response.Succeeded)
                {
                    var workOrderHeaderViewModel = _mapper.Map<WorkOrderHeaderViewModel>(response.Data.FirstOrDefault());
                    foreach (var wo in workOrderHeaderViewModel.WorkOrders)
                    {
                        foreach (var woi in wo.WorkOrderItems)
                        {
                            if (woi.WorkActivities.Any())
                            {
                                workOrderHeaderViewModel.WorkActivities.AddRange(woi.WorkActivities);
                            }
                        }
                    }
                    var usersViewModel = _mapper.Map<List<UserViewModel>>(_identityContext.Users.Where(user => user.IsActive == true).ToList());

                    workOrderHeaderViewModel.UsersSelectList = new SelectList(usersViewModel, nameof(UserViewModel.Id), nameof(UserViewModel.FirstAndLastName), null, null);

                    //var waListGroup = workOrderHeaderViewModel.WorkActivities.GroupBy(x => x.ProductStation.Station.Id).Select(grp => new WorkActivityGroupViewModel
                    //{
                    //    Activities = grp.Select(x => x).ToList(),
                    //    UsersList = grp.First().AssignedUsersIds == null ? new string[] { } : grp.First().AssignedUsersIds.Split(','),
                    //    GroupStationId = grp.First().ProductStation.Station.Id,
                    //    UsersSelectList = StationUserSelectList(grp.First().ProductStation.Station.Users),
                    //    FinishedQuantity = (grp.Where(x => x.isFinished).Count()),
                    //    Quantity = grp.Count(),
                    //});

                    var waListGroup = workOrderHeaderViewModel.WorkActivities.GroupBy(x => x.ProductStation.Station.Id).Select(grp => new WorkActivityGroupViewModel
                    {
                        Activities = grp.Select(x => x).ToList(),
                        UsersList = grp.All(x => x.AssignedUsersIds == null) ? new string[] { } : grp.Where(x => x.AssignedUsersIds != null && x.LastModifiedOn.HasValue).OrderByDescending(x => x.LastModifiedOn.Value).Select(x => x.AssignedUsersIds.Split(',')).First(),
                        GroupStationId = grp.First().ProductStation.Station.Id,
                        UsersSelectList = StationUserSelectList(grp.First().ProductStation.Station.Users),
                        FinishedQuantity = (grp.Where(x => x.isFinished).Count()),
                        Quantity = grp.Count(),
                    });

                    workOrderHeaderViewModel.WorkActivitiesGroupsByStation = waListGroup.ToList();

                    foreach (var actGroup in workOrderHeaderViewModel.WorkActivitiesGroupsByStation)
                    {
                        // Agrupo las actividades de cada puesto para poder obtener correctamente el porcentaje de avance según los agrupamientos en cada puesto.
                        var responsestation = await _stationViewManager.GetByIdAsync(actGroup.GroupStationId);
                        if (responsestation.Succeeded)
                        {
                            var stationViewModel = _mapper.Map<StationViewModel>(responsestation.Data);

                            // Filtrar la informacion según de que tipo de planilla se trate.
                            actGroup.Activities = await filterWAInformationByStock(actGroup.Activities, stationViewModel);

                            switch (stationViewModel.WorkOrderDisplayType)
                            {
                                case Stations.Torno:
                                    removeChilds(actGroup.Activities);
                                    actGroup.Activities = actGroup.Activities.GroupBy(act => act.WorkOrderItem.Product.Code).Select(grp => grp.FirstOrDefault()).ToList();
                                    break;
                                case Stations.Soldadura:
                                    removeChilds(actGroup.Activities);
                                    actGroup.Activities = actGroup.Activities.GroupBy(act => act.WorkOrderItem.Product.Code).Select(grp => grp.FirstOrDefault()).ToList();
                                    break;
                                case Stations.Montaje:
                                    removeChilds(actGroup.Activities);
                                    actGroup.Activities = actGroup.Activities.GroupBy(act => act.WorkOrderItem.Product.Code).Select(grp => grp.FirstOrDefault()).ToList();
                                    break;
                                case Stations.Laser:
                                    actGroup.Activities = actGroup.Activities.GroupBy(act => act.WorkOrderItem.Product.ProductFeature.RawMaterialCode).Select(grp => grp.FirstOrDefault()).ToList();
                                    break;
                                case Stations.Serrucho:
                                    actGroup.Activities = actGroup.Activities.GroupBy(act => act.WorkOrderItem.Product.ProductFeature.RawMaterialCode).Select(grp => grp.FirstOrDefault()).ToList();
                                    break;
                                case Stations.Envios:
                                    actGroup.Activities = actGroup.Activities.GroupBy(act => act.WorkOrderItem.Product.Code).Select(grp => grp.FirstOrDefault()).ToList();
                                    break;
                                case Stations.Abastecimientos:
                                    actGroup.Activities = actGroup.Activities.GroupBy(act => act.WorkOrderItem.Product.Code).Select(grp => grp.FirstOrDefault()).ToList();
                                    break;
                                default:
                                    actGroup.Activities = actGroup.Activities.GroupBy(act => act.WorkOrderItem.Product.ProductFeature.RawMaterialCode).Select(grp => grp.FirstOrDefault()).ToList();
                                    break;
                            }
                        }
                    }

                    // Para ordenar el listado de puestos de trabajo segun area funcional y abreviatura del puesto.
                    workOrderHeaderViewModel.WorkActivitiesGroupsByStation = workOrderHeaderViewModel.WorkActivitiesGroupsByStation.OrderBy(wgbs => wgbs.GroupStation != null ? wgbs.GroupStation.FunctionalArea.Order : wgbs.GroupStationId).ThenBy(wgbs => wgbs.GroupStation.Abbreviation).ToList();

                    return new JsonResult(new { isValid = true, html = await _viewRenderer.RenderViewToStringAsync("_ViewDetails", workOrderHeaderViewModel) });
                }
                return null;
            }
            catch (Exception ex)
            {
                _notify.Error(ex.Message);

                return new JsonResult(new { isValid = false });
            }

        }

        // Tarjeta trello: "Que dejar y sacar de stock en OTs"; Archivo excel: "Caracteristicas de OTs por puesto.xlsx" 
        public async Task<List<WorkActivityViewModel>> filterWAInformationByStock(List<WorkActivityViewModel> workActivitiesVM, StationViewModel stationViewModel)
        {
            try
            {

ERP.Web/Areas/Production/Views/WorkOrderHeader/_ViewDetails.cshtml
@using Microsoft.AspNetCore.Mvc.Localization
@using ERP.Web.Areas.Production.Models
@inject IHtmlLocalizer<ERP.Language.SharedResource> localizer

@model WorkOrderHeaderViewModel
@{
    int index = 0;
}

<form id="create-form" method="post" asp-controller="WorkOrderHeader" asp-action="AssignUsersToActivities" asp-route-id="@Model.Id" onsubmit="return jQueryModalPostWithoutRefresh(this);" enctype="multipart/form-data">
    <div class="form-row p-2">

        <div class="col-md-12 d-flex pl-0">
            <div class="col-md-1 mb-3 pl-0">
                <label class="control-label">@localizer["Nº WO"]</label>
                <input type="text" asp-for="WorkOrderHeaderNumber" readonly class="form-control text-center" />
            </div>
            <div class="col-md-2 mb-3">
                <label asp-for="CreatedOn" class="control-label">@localizer["Date of creation"]</label>
                <input type="text" name="CreatedOn" asp-for="CreatedOn" class="form-control" readonly />
            </div>
        </div>

        @if (Model.WorkOrders.Count() > 1)
        {

            var workOrderIds = "";
            var sparesOrStock = "";
            foreach (var wo in Model.WorkOrders)
            {
                workOrderIds += wo.Id + ",";
                if (wo.OrderDetail.ProductNumber.StartsWith("03"))
                {
                    sparesOrStock = "Repuestos";
                }
                if (wo.OrderDetail.ProductNumber.StartsWith("04"))
                {
                    sparesOrStock = "Stock";
                }
            }

            <label class="control-label">@localizer["Products"]</label>
            <div class="col-md-12 d-flex align-items-end w-100 pt-2 pl-0">

                @*<input type="hidden" name="item.Id" value="@item.Id" />*@

                <div class="col-md-2 mb-2 pl-0">
                    <label class="control-label border-bottom w-100">@localizer["Nº Product"]</label>
                    <input type="text" value="@sparesOrStock" readonly class="form-control" />
                </div>

                <div class="col-md-3 mb-2">
                    <label class="control-label border-bottom w-100">@localizer["Product"]</label>
                    <input type="text" value="Varios" readonly class="form-control" />
                </div>

                <div class="col-md-2 mb-2 text-center">
                    <label class="control-label border-bottom w-100 text-center">@localizer["Advance detail"]</label>
                    <a class="btn action-btn pt-2" asp-area="Production" asp-controller="WorkOrder" asp-action="LoadWorkOrderForSparesOrStock" asp-route-workOrderIds="@workOrderIds.TrimEnd(',').ToString()" title="@localizer["Percentage of completion"]">
                        <img class="action-img-icon" src="../../../images/Avance.svg" width="20" height="20" />
                    </a>
                </div>

            </div>
        }
        else
        {
            @foreach (var item in Model.WorkOrders)
            {
                @if (index == 0)
                {

                    <label class="control-label">@localizer["Products"]</label>

                    <div class="row w-100 border-bottom my-3 ml-0">
                        <div class="col-md-2 mb-2 pl-0 text-left">
                            <label asp-for="@item.OrderDetail.ProductNumber" class="control-label w-100">@localizer["Nº Product"]</label>
                        </div>

                        <div class="col-md-3 mb-2 text-left">
                            <label asp-for="@item.OrderDetail.Product.CodeAndDescription" class="control-label w-100">@localizer["Product"]</label>
                        </div>

                        @if (item.OrderDetail.Structure != null)
                        {
                            <div class="col-md-3 mb-2 text-left">
                                <label asp-for="@item.OrderDetail.Structure.Description" class="control-label w-100">@localizer["Configuration"]</label>
                            </div>
                        }
                        else
                        {
                            <div class="col-md-3 mb-2 text-left">
                                <label class="control-label w-100">@localizer["Configuration"]</label>
                            </div>
                        }

                        <div class="col-md-2 mb-2 text-left">
                            <label asp-for="@item.OrderDetail.Quantity" class="control-label w-100">@localizer["Quantity"]</label>
                        </div>

                        <div class="col-md-2 mb-2 text-left">
                            <label class="control-label w-100 text-center">@localizer["Advance detail"]</label>
                        </div>
                    </div>

                    <div class="col-md-12 d-flex align-items-end w-100 pl-0">

                        <input type="hidden" name="item.Id" value="@item.Id" />

                        <div class="col-md-2 mb-2 pl-0 text-left">
                            @*<label asp-for="@item.OrderDetail.ProductNumber" class="control-label border-bottom w-100">@localizer["Nº Product"]</label>*@
                            <input type="text" value="@item.OrderDetail.ProductNumber" readonly class="form-control" />
                        </div>

                        <div class="col-md-3 mb-2 text-left">
                            @*<label asp-for="@item.OrderDetail.Product.CodeAndDescription" class="control-label border-bottom w-100">@localizer["Product"]</label>*@
                            <input type="text" value="@item.OrderDetail.Product.CodeAndDescription" readonly class="form-control" />
                        </div>

                        @if (item.OrderDetail.Structure != null)
                        {
                            <div class="col-md-3 mb-2 text-left">
                                @*<label asp-for="@item.OrderDetail.Structure.Description" class="control-label border-bottom w-100">@localizer["Configuration"]</label>*@
                                <input type="text" value="@item.OrderDetail.Structure.Description" readonly class="form-control" />
                            </div>
                        }
                        else
                        {
                            <div class="col-md-3 mb-2 text-left">
                                @*<label class="control-label border-bottom w-100">@localizer["Configuration"]</label>*@
                                <input type="text" value="" readonly class="form-control" />
                            </div>
                        }

                        <div class="col-md-2 mb-2 text-left">
                            @*<label asp-for="@item.OrderDetail.Quantity" class="control-label border-bottom w-100">@localizer["Quantity"]</label>*@
                            <input type="text" value="@Math.Round(item.OrderDetail.Quantity, 2)" readonly class="form-control text-center" />
                        </div>

                        <div class="col-md-2 mb-2 text-center">
                            @*<label class="control-label border-bottom w-100 text-center">@localizer["Advance detail"]</label>*@
                            <a class="btn action-btn pt-2" asp-area="Production" asp-controller="WorkOrder" asp-action="LoadWorkOrder" asp-route-workorderId="@item.Id" title="@localizer["Percentage of completion"]">
                                <img class="action-img-icon" src="../../../images/Avance.svg" width="20" height="20" />
                            </a>
                        </div>

                    </div>

                }
                else
                {
                    <div class="col-md-12 d-flex align-items-end w-100 pt-2">

                        <input type="hidden" name="item.Id" value="@item.Id" />

                        <div class="col-md-2 mb-2">
                            <input type="text" value="@item.OrderDetail.ProductNumber" readonly class="form-control" />
                        </div>

                        <div class="col-md-3 mb-2">
                            <input type="text" value="@item.OrderDetail.Product.CodeAndDescription" readonly class="form-control" />
                        </div>

                        @if (item.OrderDetail.Structure != null)
                        {
                            <div class="col-md-3 mb-2">
                                <input type="text" value="@item.OrderDetail.Structure.Description" readonly class="form-control" />
                            </div>
                        }
                        else
                        {
                            <div class="col-md-3 mb-2">
                                <input type="text" value="" readonly class="form-control" />
                            </div>
                        }

                        <div class="col-md-2 mb-2">
                            <input type="text" value="@Math.Round(item.OrderDetail.Quantity, 2)" readonly class="form-control text-center" />
                        </div>

                        <div class="col-md-2 mb-2 text-center">
                            <a class="btn action-btn pt-2" asp-area="Production" asp-controller="WorkOrder" asp-action="LoadWorkOrder" asp-route-workorderId="@item.Id" title="@localizer["Percentage of completion"]">
                                <img class="action-img-icon" src="../../../images/Avance.svg" width="20" height="20" />
                            </a>
                        </div>

                    </div>
                }

                index++;

            }

        }

        <div class="col-md-12 pt-3 pl-0">
            <label class="control-label">@localizer["Processes"]</label>
        </div>

        @if (!Model.WorkActivitiesGroupsByStation.All(wags => wags.IsGroupActive))
        {
            <button id="btn-enable-all" class="btn btn-secondary">@localizer["Enable all"]</button>
        }
        else
        {
            <button id="btn-enable-all" class="btn btn-secondary" disabled>@localizer["Enable all"]</button>
        }
        
        <div class="row w-100 border-bottom my-3 ml-0">
            <div class="col-md-1 text-left">
                <label> @localizer["Actions"]</label>
            </div>
            <div class="col-md-4 text-left">
                <label> @localizer["Station"]</label>
            </div>
            <div class="col-md-4 text-left">
                <label> @localizer["Users"]</label>
            </div>
            <div class="col-md-3 text-left">
                <label> @localizer["Advance"]</label>
            </div>
        </div>
        <partial name="_ActivitiesState" model="@Model" />
    </div>
    <div id="buttons-div" class="form-group justify-content-between">
        <button id="btn-save" type="submit" class="btn btn-primary">@localizer["Save"]</button>
        <button type="submit" class="btn btn-default close-button" data-dismiss="modal"> @localizer["Cancel"]</button>
    </div>
</form>