ERP.Web/Areas/Admin/Models/RoleViewModel.cs
namespace ERP.Web.Areas.Admin.Models
{
    public class RoleViewModel
    {
        public string Name { get; set; }
        public string Id { get; set; }
    }
}

ERP.Web/Areas/Admin/Controllers/RoleController.cs
using ERP.Application.Enums;
using ERP.Infrastructure.Identity.Models;
using ERP.Language;
using ERP.Web.Abstractions;
using ERP.Web.Areas.Admin.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Localization;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace ERP.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class RoleController : BaseController<RoleController>
    {
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IStringLocalizer<SharedResource> _localizer;

        public RoleController(UserManager<ApplicationUser> userManager,
            RoleManager<IdentityRole> roleManager,
            IStringLocalizer<SharedResource> localizer)
        {
            _userManager = userManager;
            _roleManager = roleManager;
            _localizer = localizer;
        }

        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> LoadAll()
        {
            var roles = await _roleManager.Roles.ToListAsync();
            var model = _mapper.Map<IEnumerable<RoleViewModel>>(roles);
            return PartialView("_ViewAll", model);
        }

        public async Task<IActionResult> OnGetCreate(string id)
        {
            if (string.IsNullOrEmpty(id))
                return new JsonResult(new { isValid = true, html = await _viewRenderer.RenderViewToStringAsync("_Create", new RoleViewModel()) });
            else
            {
                var role = await _roleManager.FindByIdAsync(id);
                if (role == null) _notify.Error(_localizer["Unexpected Error. Role not found!"]);
                var roleviewModel = _mapper.Map<RoleViewModel>(role);
                return new JsonResult(new { isValid = true, html = await _viewRenderer.RenderViewToStringAsync("_Create", roleviewModel) });
            }
        }

        [HttpPost]
        public async Task<IActionResult> OnPostCreate(RoleViewModel role)
        {
            if (ModelState.IsValid && role.Name != Roles.SuperAdmin.ToString() && role.Name != Roles.Basic.ToString())
            {
                if (string.IsNullOrEmpty(role.Id))
                {
                    await _roleManager.CreateAsync(new IdentityRole(role.Name));
                    _notify.Success(_localizer["Role Created"]);
                }
                else
                {
                    var existingRole = await _roleManager.FindByIdAsync(role.Id);
                    existingRole.Name = role.Name;
                    existingRole.NormalizedName = role.Name.ToUpper();
                    await _roleManager.UpdateAsync(existingRole);
                    _notify.Success(_localizer["Role Updated"]);
                }

                var roles = await _roleManager.Roles.ToListAsync();
                var mappedRoles = _mapper.Map<IEnumerable<RoleViewModel>>(roles);
                var html = await _viewRenderer.RenderViewToStringAsync("_ViewAll", mappedRoles);
                return new JsonResult(new { isValid = true, html = html });
            }
            else
            {
                var html = await _viewRenderer.RenderViewToStringAsync<RoleViewModel>("_CreateOrEdit", role);
                return new JsonResult(new { isValid = false, html = html });
            }
        }

        public async Task<JsonResult> OnPostDelete(string id)
        {
            var existingRole = await _roleManager.FindByIdAsync(id);
            if (existingRole.Name != Roles.SuperAdmin.ToString() && existingRole.Name != Roles.Basic.ToString())
            {
                //TODO Check if Any Users already uses this Role
                bool roleIsNotUsed = true;
                var allUsers = await _userManager.Users.ToListAsync();
                foreach (var user in allUsers)
                {
                    if (await _userManager.IsInRoleAsync(user, existingRole.Name))
                    {
                        roleIsNotUsed = false;
                    }
                }
                if (roleIsNotUsed)
                {
                    await _roleManager.DeleteAsync(existingRole);
                    _notify.Success(_localizer["Role {0} deleted.", existingRole.Name]);
                }
                else
                {
                    _notify.Error(_localizer["Role is being Used by another User. Cannot Delete."]);
                }
            }
            else
            {
                _notify.Error(_localizer["Not allowed to delete {0} Role.", existingRole.Name]);
            }
            var roles = await _roleManager.Roles.ToListAsync();
            var mappedRoles = _mapper.Map<IEnumerable<RoleViewModel>>(roles);
            var html = await _viewRenderer.RenderViewToStringAsync("_ViewAll", mappedRoles);
            return new JsonResult(new { isValid = true, html = html });
        }
    }
}

ERP.Web/Areas/Admin/Views/Role/Index.cshtml
@using Microsoft.AspNetCore.Mvc.Localization
@inject IHtmlLocalizer<ERP.Language.SharedResource> localizer
@{
    ViewData["Title"] = localizer["Roles"];
    ViewData["Caption"] = localizer["Manage Roles here"];
}
<div class="card">
    <div id="viewAll" class="card-body table-responsive">
    </div>
</div>
@section Scripts
{
    <script src="~/js/site.js"></script>
    <script>
        $(document).ready(function () {
            $("#roleTable").DataTable({ "oLanguage": @localizer["LanguageDataTable"] });
            loadData();
            $('#reload').on('click', function () {
                loadData();
            });
        });
        function loadData() {
            $('#viewAll').load('/admin/role/LoadAll');
        }
    </script>
}

ERP.Web/Areas/Admin/Views/Role/_Create.cshtml
@using ERP.Web.Areas.Admin.Models
@using Microsoft.AspNetCore.Mvc.Localization
@inject IHtmlLocalizer<ERP.Language.SharedResource> localizer

@model RoleViewModel
<form id="create-form" method="post" asp-area="Admin" asp-controller="Role" asp-route-id="@Model.Id" asp-action="OnPostCreate" onsubmit="return jQueryModalPost(this);">
    <div class="form-group row">
        <label class="col-md-3 col-form-label">@localizer["Name"]</label>
        <div class="col-md-9">
            <input type="text" asp-for="Name" name="Name" class="form-control">
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group justify-content-between" style="margin-bottom: 0px !important">
        <button type="submit" class="btn btn-primary">@localizer["Save"]</button>
        <button type="submit" class="btn btn-default close-button" data-dismiss="modal">@localizer["Cancel"]</button>
    </div>
</form>
<script type="text/javascript" language=javascript>
    $.validator.unobtrusive.parse(document);
</script>

ERP.Web/Areas/Admin/Views/Role/_ViewAll.cshtml
@using ERP.Application.Enums
@using ERP.Web.Areas.Admin.Models
@using Microsoft.AspNetCore.Mvc.Localization
@inject IHtmlLocalizer<ERP.Language.SharedResource> localizer
@model IEnumerable<RoleViewModel>
<div id="div-export-buttons">
    <div class="btn-group">
        <a class="btn bg-secondary" onclick="jQueryModalGet('/admin/role/OnGetCreate','Create Role')">
            <i class="fa fa-plus-square"></i> 
        </a>
    </div>  
</div>
<table class="table table-striped-blue" id="roleTable">
    <thead class="bg-thead">
        <tr>
            <th style="width:10%">
                @localizer["Actions"]
            </th>
            <th>
                @localizer["Role"]
            </th>
        </tr>
    </thead>
    <tbody>

        @foreach (var role in Model)
        {
            <tr>
                <td class="text-left">
                    <div class="btn-group">
                        <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            @localizer["Action"]
                        </button>
                        <div class="dropdown-menu shadow animated--grow-in">
                            <a onclick="jQueryModalGet('/admin/role/OnGetCreate?id=@role.Id','Edit Role')" class="dropdown-item">
                                <img class="action-img-icon" src="../../../images/Editar.svg" width="20" height="20" /> @localizer["Edit"]
                            </a>
                            <form id="form_delete_@role.Id" asp-controller="Role" method="post" asp-action="OnPostDelete" asp-route-id="@role.Id" onsubmit="return jQueryModalDelete(this, '@localizer["Are you sure to delete this record?"]')" class="d-inline">
                                <a href="javascript:$('#form_delete_@role.Id').submit();" class="dropdown-item"><img class="action-img-icon" src="../../../images/Eliminar.svg" width="20" height="20" /> @localizer["Delete"]</a>
                            </form>
                            @if (role.Name != Roles.SuperAdmin.ToString())
                            {

                                <a style='margin-right:16px' asp-controller="Permission" asp-action="Index" asp-route-roleId="@role.Id" class="dropdown-item">
                                    <i class="fas fa-wrench"></i> @localizer["Manage Permissions"]
                                </a>
                            }
                        </div>
                    </div>
                </td>
                <td>
                    @role.Name
                </td>               
            </tr>
        }
    </tbody>
    <tfoot>
        <tr>
            <th style="width:10%">
                @localizer["Actions"]
            </th>
            <th>
                @localizer["Role"]
            </th>
        </tr>
    </tfoot>
</table>
<script>
    $(document).ready(function () {

        $('#roleTable tfoot th').each(function (i) {
            var title = $(this).text().trim();
            if (title != "@localizer["Actions"]") {
                $(this).html('<input type="text" class="search-control text-left" placeholder="' + title.trim() + '" data-index="' + i + '" />');
            } else {
                $(this).html('');
            }
        });

        $("#roleTable").DataTable({
            "oLanguage": @localizer["LanguageDataTable"],
            "scrollY": '55vh',
            "scrollCollapse": true,
            "scroller": true,
            "order": [
                [1, "desc"]
            ],
            initComplete: function () {
                this.api().columns().every(function () {
                    var that = this;
                    $('input', this.footer()).on('keyup change clear', function () {
                        if (that.search() !== this.value) {
                            that
                                .search(this.value)
                                .draw();
                        }
                    });
                });

                $("#roleTable_filter").addClass("d-none");

            }
            
        });
    });
</script>