ERP.Web/Areas/ProductMod/Models/StationViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
namespace ERP.Web.Areas.ProductMod.Models
{
    public class StationViewModel
    {
        public int Id { get; set; }
        public string Description { get; set; }
        public bool IsActive { get; set; }
        public string Abbreviation { get; set; }
        public string WorkOrderDisplayType { get; set; }
        public SelectList FunctionalAreas { get; set; }
        public int FunctionalAreaId { get; set; }
        public FunctionalAreaViewModel FunctionalArea { get; set; }
        public string DefaultUser { get; set; }
        public string Users { get; set; }
        public string[] UsersIds { get; set; }
        public SelectList UsersSelectList { get; set; }
        public int ConcurrencyToken { get; set; }

        public string AbreviationDescription
        {
            get
            {
                return this.Abbreviation + " - " + this.Description;
            }
        }
    }
}

ERP.Web/Areas/ProductMod/Controllers/StationController.cs
using ERP.Application.Constants;
using ERP.Application.DTOs.Entities.ProductMod;
using ERP.Application.Interfaces.ViewManagers.ProductMod;
using ERP.Infrastructure.DbContexts;
using ERP.Infrastructure.Identity.Models;
using ERP.Language;
using ERP.Web.Abstractions;
using ERP.Web.Areas.Admin.Models;
using ERP.Web.Areas.ProductMod.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Localization;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ERP.Web.Areas.ProductMod.Controllers
{
    [Area("ProductMod")]
    public class StationController : BaseController<StationController>
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IStationViewManager _viewManager;
        private readonly IFunctionalAreaViewManager _functionalareaviewManager;
        private readonly IStringLocalizer<SharedResource> _localizer;
        private IdentityContext _identityContext;
        public StationController(IStationViewManager viewManager, IFunctionalAreaViewManager functionalareaviewManager, UserManager<ApplicationUser> userManager, IdentityContext identityContext, IStringLocalizer<SharedResource> localizer)
        {
            _viewManager = viewManager;
            _functionalareaviewManager = functionalareaviewManager;
            _userManager = userManager;
            _localizer = localizer;
            _identityContext = identityContext;
        }

        public IActionResult Index()
        {
            var model = new StationViewModel();
            return View(model);
        }

        public async Task<IActionResult> LoadAll()
        {
            var response = await _viewManager.LoadAllWithFunctionalArea();
            if (response.Succeeded)
            {
                var viewModel = _mapper.Map<List<StationViewModel>>(response.Data);
                return PartialView("_ViewAll", viewModel.OrderBy(st => st.FunctionalArea.Order).ToList());
            }
            return null;
        }

        [Authorize(Policy = Permissions.Stations.View)]
        public async Task<JsonResult> OnGetCreateOrEdit(int id = 0)
        {
            try
            {
                var functionalareaResponse = await _functionalareaviewManager.GetAllFunctionalAreas();
                var usersViewModel = _mapper.Map<List<UserViewModel>>(_identityContext.Users.Where(user => user.IsActive == true).ToList());
                if (id == 0)
                {
                    var stationViewModel = new StationViewModel();
                    stationViewModel.UsersSelectList = new SelectList(usersViewModel, nameof(UserViewModel.Id), nameof(UserViewModel.FirstAndLastName), null, null);
                    if (functionalareaResponse.Succeeded)
                    {
                        var functionalareasViewModel = _mapper.Map<List<FunctionalAreaDTO>>(functionalareaResponse.Data);
                        stationViewModel.FunctionalAreas = new SelectList(functionalareasViewModel, nameof(FunctionalAreaViewModel.Id), nameof(FunctionalAreaViewModel.Description), null, null);
                    }
                    return new JsonResult(new { isValid = true, html = await _viewRenderer.RenderViewToStringAsync("_CreateOrEdit", stationViewModel) });
                }
                else
                {
                    var response = await _viewManager.GetByIdAsync(id);
                    if (response.Succeeded)
                    {
                        var stationViewModel = _mapper.Map<StationViewModel>(response.Data);
                        if (stationViewModel.Users != null)
                        {
                            stationViewModel.UsersIds = stationViewModel.Users.Split(',');
                        }
                        stationViewModel.UsersSelectList = new SelectList(usersViewModel, nameof(UserViewModel.Id), nameof(UserViewModel.FirstAndLastName), null, null);
                        if (functionalareaResponse.Succeeded)
                        {
                            var functionalareasViewModel = _mapper.Map<List<FunctionalAreaDTO>>(functionalareaResponse.Data);
                            stationViewModel.FunctionalAreas = new SelectList(functionalareasViewModel, nameof(FunctionalAreaViewModel.Id), nameof(FunctionalAreaViewModel.Description), null, null);
                        }
                        return new JsonResult(new { isValid = true, html = await _viewRenderer.RenderViewToStringAsync("_CreateOrEdit", stationViewModel) });
                    }
                    return null;
                }
            }
            catch (Exception ex)
            {

                throw ex;
            }

        }

        [HttpPost]
        public async Task<JsonResult> OnPostCreateOrEdit(int id, StationViewModel station, string[] UsersIds)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    if (station.DefaultUser != null && !UsersIds.Any(id => id.Equals(station.DefaultUser)))
                    {
                        List<string> list = UsersIds.ToList();
                        list.Add(station.DefaultUser);
                        UsersIds = list.ToArray();
                    }
                    var concantIds = string.Join(',', UsersIds);
                    if (id == 0)
                    {
                        station.Users = concantIds;
                        var stationDTO = _mapper.Map<StationDTO>(station);
                        var result = await _viewManager.CreateAsync(stationDTO);
                        if (result.Succeeded)
                        {
                            id = result.Data;
                            _notify.Success(_localizer["Station with ID {0} Created.", result.Data]);
                        }
                        else _notify.Error(result.Message);
                    }
                    else
                    {
                        station.Users = concantIds;
                        var stationDTO = _mapper.Map<StationDTO>(station);
                        var result = await _viewManager.UpdateAsync(stationDTO);
                        if (result.Succeeded) _notify.Information(_localizer["Station with ID {0} Update.", result.Data]);
                    }

                    var response = await _viewManager.LoadAllWithFunctionalArea();
                    if (response.Succeeded)
                    {
                        var viewModel = _mapper.Map<List<StationViewModel>>(response.Data);
                        var html = await _viewRenderer.RenderViewToStringAsync("_ViewAll", viewModel);
                        return new JsonResult(new { isValid = true, html = html });
                    }
                    else
                    {
                        _notify.Error(response.Message);
                        return null;
                    }
                }
                else
                {
                    var html = await _viewRenderer.RenderViewToStringAsync("_CreateOrEdit", station);
                    return new JsonResult(new { isValid = false, html = html });
                }
            }
            catch (Exception ex)
            {
                _notify.Error(ex.Message);
                var html = await _viewRenderer.RenderViewToStringAsync("_CreateOrEdit", station);
                return new JsonResult(new { isValid = false, html = html });
            }
        }

        [HttpPost]
        public async Task<JsonResult> OnPostDelete(int id)
        {
            var deleteCommand = await _viewManager.DeleteAsync(id);
            if (deleteCommand.Succeeded)
            {
                _notify.Information(_localizer["Station with ID {0} Deleted.", id]);
                var response = await _viewManager.LoadAllWithFunctionalArea();
                if (response.Succeeded)
                {
                    var viewModel = _mapper.Map<List<StationViewModel>>(response.Data);
                    var html = await _viewRenderer.RenderViewToStringAsync("_ViewAll", viewModel);
                    return new JsonResult(new { isValid = true, html = html });
                }
                else
                {
                    _notify.Error(response.Message);
                    return new JsonResult(new { isValid = false });
                }
            }
            else
            {
                _notify.Error(deleteCommand.Message);
                return new JsonResult(new { isValid = false });
            }
        }
    }
}

ERP.Web/Areas/ProductMod/Views/Station/Index.cshtml
@using Microsoft.AspNetCore.Mvc.Localization
@inject IHtmlLocalizer<ERP.Language.SharedResource> localizer
@{
    ViewData["Title"] = localizer["Work stations"];
    //ViewData["Caption"] = localizer["Manage Stations here"];
}
@using ERP.Web.Areas.ProductMod.Models
@model StationViewModel

    <head>
        <link href="~/css/Lists/lists.css" rel="stylesheet" />
    </head>

    <div class="card">

        <div id="viewAll" class="card-body table-responsive">
        </div>

    </div>
    @section Scripts
{
        <script>
        $(document).ready(function () {
            $("#stationTable").DataTable({ "oLanguage": @localizer["LanguageDataTable"] });
            loadData();
            $('#reload').on('click', function () {
                loadData();
            });
        });
        function loadData() {
            $('#viewAll').load('/productmod/station/LoadAll');
        }
        </script>
    }

ERP.Web/Areas/ProductMod/Views/Station/_CreateOrEdit.cshtml
@using Microsoft.AspNetCore.Mvc.Localization
@using ERP.Web.Areas.ProductMod.Models
@inject IHtmlLocalizer<ERP.Language.SharedResource> localizer

@model StationViewModel
<form id="create-form" method="post" asp-controller="Station" asp-action="OnPostCreateOrEdit" asp-route-id="@Model.Id" onsubmit="return jQueryModalPost(this);" enctype="multipart/form-data">
    <div class="row">
        <div class="col-md-12">
            <div class="form-group row">
                <div class="col-md-9">
                    <input type="hidden" asp-for="ConcurrencyToken" name="ConcurrencyToken" class="form-control">
                </div>
            </div>
            <div class="form-group row">
                <label class="col-md-3 col-form-label">@localizer["Code"]</label>
                <div class="col-md-9">
                    <input type="text" asp-for="Abbreviation" name="Abbreviation" class="form-control">
                    <span asp-validation-for="Abbreviation" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group row">
                <label class="col-md-3 col-form-label">@localizer["Description"]</label>
                <div class="col-md-9">
                    <input type="text" asp-for="Description" name="Description" class="form-control">
                    <span asp-validation-for="Description" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group row">
                <label class="col-md-3 col-form-label"> @localizer["Functional area"]</label>
                <div class="col-md-9">
                    <div class="input-group">
                        @Html.DropDownListFor(m => m.FunctionalAreaId, Model.FunctionalAreas, "----------", new { @class = "form-control" })
                    </div>
                    <span class="text-danger" asp-validation-for="FunctionalAreaId"></span>
                </div>
            </div>
            <div class="form-group row">
                <label class="col-md-3 col-form-label"> @localizer["Station´s users"]</label>
                <div class="col-md-9">
                    <div class="input-group row-col-md-12">
                        <div class="input-group">
                            @*@Html.DropDownList("AccessoryProduct", Model.AccessoryProductsList, "----------", new { @class = "form-control" })*@
                            <select class="form-control select2bs4" multiple="multiple" id="UsersIds" name="UsersIds" asp-for="UsersIds" asp-items="@Model.UsersSelectList">
                            </select>
                        </div>
                    </div>
                </div>
            </div>
            <div class="form-group row">
                <label class="col-md-3 col-form-label"> @localizer["Default user"]</label>
                <div class="col-md-9">
                    <div class="input-group">
                        @Html.DropDownListFor(m => m.DefaultUser, Model.UsersSelectList, "----------", new { @class = "form-control" })
                    </div>
                    <span class="text-danger" asp-validation-for="DefaultUser"></span>
                </div>
            </div>
            <div class="form-group row">
                <label class="col-md-3 col-form-label"> @localizer["Work order display"]</label>
                <div class="col-md-9">
                    <div class="input-group">
                        <select name="WorkOrderDisplayType" class="form-control select2bs4" id="WorkOrderDisplayType" asp-for="WorkOrderDisplayType">
                            <option value="">@localizer["Select an option"]</option>
                            <option value="Serrucho">@localizer["OT Serrucho"]</option>
                            <option value="Laser">@localizer["OT Laser"]</option>
                            <option value="Torno">@localizer["OT Torno"]</option>
                            <option value="Soldadura">@localizer["OT Soldadura"]</option>
                            <option value="Montaje">@localizer["OT Montaje"]</option>
                            <option value="Envios">@localizer["OT Envios"]</option>
                            <option value="Abastecimientos">@localizer["OT Abastecimientos"]</option>
                            <option value="Entregas">@localizer["OT Entregas"]</option>
                        </select>
                    </div>
                    <span class="text-danger" asp-validation-for="WorkOrderDisplayType"></span>
                </div>
            </div>
            <div class="form-group row">
                <label class="col-md-3 col-form-label">@localizer["State"]</label>
                <div class="col-md-9">

                    @if (Model.Id == 0 || Model.IsActive)
                    {
                        <input type="checkbox" name="IsActive" value="true" checked />
                    }
                    else
                    {
                        <input type="checkbox" name="IsActive" value="true" />
                    }
                    <label for="IsActive" class="col-form-label">@localizer["Active"]</label>
                </div>
            </div>
        </div>
    </div>

    <div class="row form-group d-flex flex-row-reverse mb-0 mt-2 align-self-end">
        <button id="btn-save" type="submit" class="btn btn-default close-button" data-dismiss="modal">@localizer["Cancel"]</button>
        <button type="submit" class="btn btn-primary text-white mr-1">@localizer["Save"]</button>

    </div>
</form>
<script type="text/javascript" language=javascript>
    $.validator.unobtrusive.parse(document);

    $("#FunctionalAreaId").select2({
        placeholder: "Seleccionar área funcional",
        language: {
            noResults: function (params) {
                return 'No se encontraron resultados';
            }
        },
        theme: "bootstrap4",
        escapeMarkup: function (m) {
            return m;
        },
        sorter: data => data.sort((a, b) => a.text.localeCompare(b.text))
    });
    $("#DefaultUser").select2({
        placeholder: "Seleccionar usuario por defecto",
        language: {
            noResults: function (params) {
                return 'No se encontraron resultados';
            }
        },
        theme: "bootstrap4",
        escapeMarkup: function (m) {
            return m;
        },
        sorter: data => data.sort((a, b) => a.text.localeCompare(b.text))
    });
    $("#UsersIds").select2({
        placeholder: "Seleccionar usuario por defecto",
        language: {
            noResults: function (params) {
                return 'No se encontraron resultados';
            }
        },
        theme: "bootstrap4",
        escapeMarkup: function (m) {
            return m;
        },
        sorter: data => data.sort((a, b) => a.text.localeCompare(b.text))
    });
    $("#WorkOrderDisplayType").select2({
        placeholder: "Seleccionar una planilla de trabajo",
        theme: "bootstrap4",
        escapeMarkup: function (m) {
            return m;
        }
    });
</script>

ERP.Web/Areas/ProductMod/Views/Station/_ViewAll.cshtml
@using ERP.Web.Areas.ProductMod.Models
@using Microsoft.AspNetCore.Mvc.Localization
@inject IHtmlLocalizer<ERP.Language.SharedResource> localizer
@model IEnumerable<StationViewModel>
<div id="div-export-buttons">
    <div class="btn-group">
        @if ((AuthorizationService.AuthorizeAsync(User, Permissions.Stations.Create)).Result.Succeeded)
        {
            <a id="btn-create" onclick="jQueryModalGet('/productmod/station/OnGetCreateOrEdit','@localizer["Create Station"]')" class="btn btn-secondary text-white">
                <i class="fa fa-plus-square"></i> 
            </a>
        }
    </div>
</div>
<table id="stationTable" class="table table-striped-blue table-hover w-100 nowrap" cellspacing="0">
    <thead class="bg-thead text-white">
        <tr>
            <th hidden>@localizer["Id"]</th>
            <th>@localizer["Actions"]</th>
            <th>@localizer["Functional area"]</th>
            <th>@localizer["Code"]</th>
            <th>@localizer["Description"]</th>
            <th>@localizer["Planilla OT"]</th>
            <th hidden></th>
        </tr>
    </thead>
    <tbody>

        @foreach (var station in Model)
        {
            <tr>
                <td hidden>
                    @station.Id
                </td>
                <td class="text-left">
                    <div class="btn-group">
                        <div class="d-flex animated--grow-in">
                            @if ((AuthorizationService.AuthorizeAsync(User, Permissions.Stations.Edit)).Result.Succeeded)
                            {
                                <a class="btn action-btn" title="@localizer["Edit"]" onclick="jQueryModalGet('/productmod/station/OnGetCreateOrEdit?id=@station.Id','@localizer["Edit Station"]')"><img class="action-img-icon" src="../../../images/Editar.svg" width="20" height="20" /></a>
                            }
                            else
                            {
                                <a class="btn action-btn disabled" title="@localizer["Edit"]" onclick="jQueryModalGet('/productmod/station/OnGetCreateOrEdit?id=@station.Id','@localizer["Edit Station"]')"><img class="action-img-icon" src="../../../images/Editar.svg" width="20" height="20" /></a>
                            }
                            @if ((AuthorizationService.AuthorizeAsync(User, Permissions.Stations.Delete)).Result.Succeeded)
                            {
                                <form id="form_delete_@station.Id" asp-area="Productmod" asp-controller="Station" method="post" asp-action="OnPostDelete" asp-route-id="@station.Id" onsubmit="return jQueryModalDelete(this, '@localizer["Are you sure to delete this record?"]')">
                                    <a class="btn action-btn" title="@localizer["Delete"]" href="javascript:$('#form_delete_@station.Id').submit();"><img class="action-img-icon" src="../../../images/Eliminar.svg" width="20" height="20" /></a>
                                </form>
                            }
                            else
                            {
                                <a class="btn action-btn disabled" title="@localizer["Delete"]" href="javascript:$('#form_delete_@station.Id').submit();"><img class="action-img-icon" src="../../../images/Eliminar.svg" width="20" height="20" /></a>
                            }
                        </div>
                    </div>
                </td>
                <td>
                    @station.FunctionalArea.Description
                </td>
                <td>
                    @station.Abbreviation
                </td>
                <td>
                    @station.Description
                </td>
                <td>
                    @station.WorkOrderDisplayType
                </td>
                <td hidden>
                    @station.FunctionalArea.Order
                </td>
            </tr>
        }
    </tbody>
    <tfoot>
        <tr>
            <th hidden>@localizer["Id"]</th>
            <th>@localizer["Actions"]</th>
            <th>@localizer["Functional area"]</th>
            <th>@localizer["Code"]</th>
            <th>@localizer["Description"]</th>
            <th>@localizer["Planilla OT"]</th>
            <th hidden></th>
        </tr>
    </tfoot>
</table>
<script>
    $(document).ready(function () {
        //Busqueda en footers de tablas
        $('#stationTable tfoot th').each(function (i) {
            var title = $(this).text();
            if (title != "@localizer["Actions"]") {
                $(this).html('<input type="text" class="search-control" placeholder="' + title + '" data-index="' + i + '" />');
            } else {
                $(this).html('');
            }
        });
        let stationTable = $("#stationTable").DataTable({
            "oLanguage": @localizer["LanguageDataTable"],
            "columnDefs": [{ "targets": [0], "visible": false, "searchable": false }],
            "dom": 'Bfrtip',
            //"order": [[2, "asc"], [3, "asc"]],
            "order": [[6, "asc"], [3, "asc"]],
            "buttons": [
                {
                    "extend": "excelHtml5",
                    "text": '<img class="tables-img-icon" src="../../../images/Excel.svg" width="25" height="25" />',
                    "titleAttr": "Exportar archivo Excel",
                    "title": "Datos puestos de trabajo",
                    "exportOptions": {
                        "columns": [2, 3, 4, 5]
                    }
                }],
            scrollY: '60vh',
            scrollX: true,
            scrollCollapse: true,
            scroller: true,
            scroller: {
                loadingIndicator: true
            }
        });

        stationTable.buttons().container()
            .appendTo("#div-export-buttons .btn-group");

        $(stationTable.table().container()).on('keyup', 'tfoot input', function () {
            stationTable
                .column($(this).data('index'))
                .search(this.value)
                .draw();
        });
    });
</script>